### ISSUE TITLE
No report of "water lack"

### ISSUE THREAD

**Issue by timothe** [formatBCE/HA_VeSync_Classic300s#11]
Thank you for this custom component, it's working well on my 300s.
The sensors are working great: humidity, water tank presence, lights.
However, even when the water tank is empty and the humidifier stops working because of it, it's never reporting it to HA.
Is that behaviour expected? Because I can't see this reported in the VeSync either.

**Comment by formatBCE** [comment]
Hi @timothe 

I will check, but the rule of thumb is: if it doesn't work in pyvesync library - I can do nothing to it.

However, my 300s is reporting on water lack. I have automation on that value, so I'd know.

Does your vendor app report on water lack? Probably, it's device defect?

**Comment by timothe** [comment]
Yeah I don't see it in the vendor app - VeSync, so I wouldn't define it as an issue with your component, but rather an awareness on this fact. I will do some more tests and let you know.

**Comment by timothe** [comment]
I confirm I have the 300S, and the VeSync app is not reporting any lack of water. Is that supposed to be that way?
On the [official page](https://levoit.com/products/classic-300s-smart-ultrasonic-top-fill-cool-mist-humidifier), there's no reference of this behaviour either.

**Comment by formatBCE** [comment]
Hmm, can't upload screenshot for some reason, but I have history of notifications for my 300s, with notification of "tank is empty", as well as "tank is lifted".
