### ISSUE TITLE
VeSync-FormatBCE has stopped working after upgrading to 2024.1.0

### ISSUE THREAD

**Issue by billmaterial** [formatBCE/HA_VeSync_Classic300s#12]
The problem
VeSync-FormatBCE has stopped working after upgrading to 2024.1.0. Device and entities are not available. The cloud service is up and running, has been checked with the VeSync app.

What version of Home Assistant Core has the issue?
2024.1.0

What was the last working version of Home Assistant Core?
2023.12.4

What type of installation are you running?
Home Assistant OS

Integration causing the issue
VeSync-FormatBCE

Link to integration documentation on our website
https://www.home-assistant.io/integrations/vesync

Diagnostics information
No response

Example YAML snippet
No response

Anything in the logs that might be useful for us?
Office Humidifier (high humidity) became unavailable
10:15:54 - 8 minutes ago
Office Humidifier (water lack) became unavailable
10:15:54 - 8 minutes ago
Office Humidifier (water tank) became unavailable
10:15:54 - 8 minutes ago
Office Humidifier (night light) became unavailable
10:15:54 - 8 minutes ago
Office Humidifier (high humidity) became unavailable
10:09:38 - 14 minutes ago
Office Humidifier (water lack) became unavailable
10:09:38 - 14 minutes ago
Office Humidifier (water tank) became unavailable
10:09:38 - 14 minutes ago
Office Humidifier (night light) became unavailable
10:09:38 - 14 minutes ago
Additional information
No response

**Comment by zzarne** [comment]
I can confirm this. A workaround - don't know if it's correct - is to change vesync_formatbce/humidifier.py line 95 to:
```
        return (SUPPORT_MODES,)
```

**Comment by billmaterial** [comment]
@zzarne thank you so much, you are a star! I can confirm it works perfectly for me.

**Comment by formatBCE** [comment]
I guess you can just delete that function all along - it's defined in base
humidifier entity.
Shame though, that it should've been deprecated not earlier than 2025.1,
according to HA code - but someone made it earlier.

Will update repo later today.

**Comment by billmaterial** [comment]
@zzarne It's not quite working perfectly yet, the mode change throws an error: Failed to call service humidifier/set_mode. unsupported operand type(s) for &:'tuple' and 'HumidifierEntityFeature'
I will look into this but my knowledge is very much lacking with this.

**Comment by formatBCE** [comment]
I'm working on correct fix.

**Comment by formatBCE** [comment]
Humidifiers working again.
