### ISSUE TITLE
Integration does not recognize Levoit Dual 200S Humidifier

### ISSUE THREAD

**Issue by jacksnchz** [formatBCE/HA_VeSync_Classic300s#17]
Hi all,

Recently I installed the integration (VeSync-FormatBCE v1.0.4) but no way to recognize the device, I removed and installed the integration with and without homeassistant restart without success.

Logs reports me next information:

`2024-08-28 12:26:48.626 WARNING (MainThread) [custom_components.vesync_formatbce.fan] Humidificador - Unknown device type - LUH-D301S-WEU`

Humidifier is working currently via manufacturer app and google home.

No core integration installed, only this one (no conflicts)

I saw in the past some users were reporting support for this model and was introduced sucessfully.

Maybe some changes in Home Assistant is causing the problem?

```
Core: 2024.8.3
Supervisor: 2024.08.0
Operating System: 13.1
```

Thank u!

**Comment by formatBCE** [comment]
Hi.
Looks like this device is supported by pyvesync library. It's humidifier, right?

I can try adding it blindly, but it would be great if you try it first, and test it's work. But it requires changing the code. Can you do it?

**Comment by formatBCE** [comment]
Wait a second. It should be there! It's in the list in integration...
And it was reported as working, yes.

**Comment by jacksnchz** [comment]
Hi!

Yes, i saw the code and it was defined in, it doesn’t make sense.

I have followed old issues related with this project and in homeassistant forums where you provide support, searching a explanation without success…

i will try other ways but I am locked.

Thank u again for your first time.

Asap i find a solution, i will post it!

**Comment by formatBCE** [comment]
What I can suggest is - try to debug with pyvesync itself. Just install it on PC, authenticate and try to get your data. It's pretty easy.

Use pyvesync 1.4.1 for precise results - it's the version used in HA integration.
