### ISSUE TITLE
Not showing in Integrations

### ISSUE THREAD

**Issue by jmadray** [formatBCE/HA_VeSync_Classic300s#5]
I've added the folder to the config/custom_components folder and restarted HomeAssistant, but the integration doesn't show up when I go to the Add Integration button.  I've installed other custom components and gotten them to work, not sure what's wrong.

**Comment by formatBCE** [comment]
> I've added the folder to the config/custom_components folder and restarted HomeAssistant, but the integration doesn't show up when I go to the Add Integration button.  I've installed other custom components and gotten them to work, not sure what's wrong.

Please try to do same from another browser, or incognito mode. This is known, that sometimes HA doesn't show new integrations in list due to cache issue.

**Comment by jmadray** [comment]
Should have replied back, I got it working now.  Thank you for all your
hard work on this integration, it helped me control my humidifier for my
snake tank.

**Comment by formatBCE** [comment]
Glad it worked out! Thanks for reaching back. :)
