### ISSUE TITLE
No devices found

### ISSUE THREAD

**Issue by lasry1** [formatBCE/HA_VeSync_Classic300s#7]
Hi I have added the integration but it doesn't seem to find any devices. On my Vesync app i can see it.

It's a dual 200S humidifier

What am i doing wrong?

Thanks

**Comment by formatBCE** [comment]
> Hi I have added the integration but it doesn't seem to find any devices. On my Vesync app i can see it.
> 
> It's a dual 200S humidifier
> 
> What am i doing wrong?
> 
> 
> Thanks

1. Please check the logs in Home Assistant. This might give some info
2. Try to use pyvesync library on your PC to find out, if it's supported. Because if not, integration won't be able to find device either.

**Comment by lasry1** [comment]
Logs doesn't mention VeSync-FormatBCE but the integration is installed and logged in.

I have tried to use pyvesync library on my mac but i can't get pass installation. after I installed i don't know how to proceed. "from pyvesync import VeSync" returns "from: can't read /var/mail/pyvesync"


The device is the Levoit dual 200s ( https://www.amazon.co.uk/gp/product/B09KT9ZK7Q/ref=ppx_yo_dt_b_asin_image_o01_s00?ie=UTF8&psc=1 )

**Comment by formatBCE** [comment]
If there's no log - means no errors. So most probably it's unsupported model.
Please read how-to in pyvesync library repo.

**Comment by lasry1** [comment]
@formatBCE it took me a while to figure how pyvesync works basically the 11 days since you point me to that repo. 

At the beginning the device wasn't initiated but Webdjoe changed something in the code I guess. ( https://github.com/webdjoe/pyvesync/issues/120 )

Now, I have it up un running in python and i can see and control my device, so i don't know why home assistant isn't finding anything.

The model is LUH-D301S-WEU and pyvesync classifies it as 'VeSyncHumid200300S' it's fully working with python (without the S between the 200 and 300 instead of 'VeSyncHumid200S300S'  as per the wiki of pyvesync)

**Comment by lasry1** [comment]
this is duplicated then with https://github.com/formatBCE/HA_VeSync_Classic300s/issues/6

I make it work with the version from SuchByte

**Comment by formatBCE** [comment]
Great, I'm glad you figured it out!
